### ISSUE TITLE
Random question about an old demo

### ISSUE THREAD

**Issue by TomArrow** [TheSil/WhoracleMod#12] opened 2022-12-30 23:36 UTC
Good day, in the course of trying to improve my demo analyzer tool, I found an old JKA CTF demo made on a "horacle" server (I can't read it quite right due to the name) and noticed that when playing back in OpenJK, the kill types are all funky. For example some guns are recognized as mine kills and pushing someone into his death results in a MOD_SUICIDE / indescript "X killed Y" message. I'm thinking this must be related to some specific mod used that had a different meansOfDeath_t enum, but for the life of me, I cannot find it. I looked in this codebase too and nothing.

In the demo configstring, the gamename is "base_enhanced" and the server version string is JAmp: v1.0.1.0 linux-i386 Apr 11 2014.

Would you happen to have any idea about what could have caused that demo to have such strange values in the EV_OBITUARY event? I thought I'd give it a shot since the server was named horacle and this codebase sounds kinda like that. Maybe you have an idea what's happening? Would be nice to maybe add a workaround for this to my demo analyzer.

**Comment by TheSil** [comment] 2022-12-31 12:05
Hey Tom, the base_enhanced is indeed a mod that was running (and its derivatives still are) on the CTF servers, it had basically many bug fixes to the vanilla, hence base_enhanced. You can ignore the WhoracleMod repo, that was intended for client mode changes which I actually never fully put to git, what you want instead is this https://github.com/TheSil/base_enhanced . And the server name was whoracle ctf pug, whoracle was an old school clan of ctf players (first letter was different color i think and there was the upside down question mark somewhere there). 

Since it was primarily for the CTF community, there were also some improvements in that regard. You might not find all changes in the commit as already the original checkout to github was when the mod was a long time in development (it's much older than 2014).

When someone falls to death but was pushed there by someone else, the vanilla would just report that as fall to his death, even though someone else was responsible. The base_enhanced had an update for this so it would be correctly attributed to the last person damaging the falling person (there were some conditions for which I do not remember exactly), so this seems like intended. So that should explain at least the falling death part. This thing was controlled by variable g_fixPitKills, which allows to find it in the code, this part was responsible for the upgrade: https://github.com/TheSil/base_enhanced/blob/71619c7de03658f274e970d3547376967710a16d/game/g_combat.c#L2228 .

About the weird mine kills, I don't know what that means nor recall any updates in this regard. Though I don't think we made any enum changes, so it is probably something intended (unless demo had some scrambled info but I doubt it would happen consistently). You might share the demo so I could look, maybe I would recall what feature was that :) - You can send it at sildak at gmail com .

**Comment by TheSil** [comment] 2022-12-31 12:17
Also unrelated somewhow but since you are making jka demo tools, I have just recently put an old tool for demo manipulation stuff into the git (after 10 years :D), tools like jamme later on when engine code was released came up with similar functionality (and the probably the one you are making) so this should now be deprecated, but I thought you might be interested. You can find it at https://github.com/TheSil/JkaDemoTools .

**Comment by TomArrow** [comment] 2022-12-31 18:18
Hey there, thanks for your response!

I see. Well the thing is, in the demo specifically, the value of mod (or eventParm) was actually the one that was MOD_COLLIDE in the original game and MOD_SUICIDE in most of the OpenJK varieties. So basically it is recognized as MOD_SUICIDE, but then through the condition of attacker == target it doesn't get treated as a suicide (because both attacker and target are filled in) but instead falls through to the normal MOD handling and there it falls through the entire switch statement (because MOD_SUICIDE isn't among the "cases") to the default which results in the generic "X killed Y" message which has the attribution of the killer, but not the true means of death. So it's not even a MOD_FALLING, which would actuallly make sense.

Here's a few pieces cut out of the demo as a zip file:
[weird demo.zip](https://github.com/TheSil/WhoracleMod/files/10327810/weird.demo.zip)

The ones marked as "COLLIDE" are the ones Im referring to (it was an early test with the original MOD_COLLIDE from the Ravensoft source code release, but the same value is what MOD_SUICIDE is in OpenJK and most mods, including this one I believe). The ones marked as "MINE" you can tell they are clearly not mine kills yet that's what they are displayed as.

In each demo the relevant moment is 10 seconds in.

(for the record, i tested the demo without cutting too, so the cutting itself didn't introduce the discrepancy, but I dont wanna force you to search through a long demo)

**Comment by TomArrow** [comment] 2022-12-31 18:19
> Also unrelated somewhow but since you are making jka demo tools, I have just recently put an old tool for demo manipulation stuff into the git (after 10 years :D), tools like jamme later on when engine code was released came up with similar functionality (and the probably the one you are making) so this should now be deprecated, but I thought you might be interested. You can find it at https://github.com/TheSil/JkaDemoTools .

Well my tools are JK2 tools originally and now I'm kinda adding JKA support, hence this quest for the truth of the matter, heh. Demo smoothing is something I have not added to my own yet, at least not as a standalone simple to use tool, but it's definitely something I'm considering to do at some point. I'll look at your code for inspiration if/when I do that, thanks!

**Comment by TheSil** [comment] 2022-12-31 20:12
Well the game is just buggy, I don't think there is anything wrong with the demo file. I looked at the closed tickets for base_enhanced and the issue with invalid golan alt message was fixed in there (after this demo is recorded). https://github.com/TheSil/base_enhanced/issues/99

It is possible the other issues got fixed later as well, but I wouldn't know if they are fixed in other mods (this mod predates OpenJK and is based on original ravensoft released code, so I guess this was always bugged).

**Comment by TomArrow** [comment] 2022-12-31 20:15
Oooh, interesting! I was convinced it was just a completely different MOD_ enum but apparently not. Thanks for finding that. It''s funny that I checked exactly the two kills that ended up being weird and assumed everything was when the rest is probably ok.

Still leaves the MOD_SUICIDE issue... but I actually had a theory a few moments ago. Is it possible that when someone is pushed into the abyss he just suicides himself and thus the means of death is suicide but the attacker is also transmitted because the game detects the reason for his suicide and gives credit to the pusher?

**Comment by TheSil** [comment] 2022-12-31 20:17
Yea i think that is correct, that is the thing I mentioned originally which is by default enabled in g_fixPitKills. It was way too common in CTF and people used selfkill command to avoid giving credit, so I added this :)

**Comment by TomArrow** [comment] 2022-12-31 20:18
Yeah now everyhing makes sense for sure. Thanks a lot for your help!

**Comment by TheSil** [comment] 2022-12-31 20:19
No problem, it was fun to open demo after many years :D Good luck with your project.

**Closed as completed by TheSil** 2022-12-31 20:19 UTC
